import path from 'node:path';
import fs from 'fs-extra';
import fg from 'fast-glob';
import type { LabConfig, LabFramework } from '@frontend-labs/lab-core';
import { repoRoot, appDirs } from '../utils/paths';
import { toTitle, toComponentName } from '../utils/slug';
import { readLabConfig } from '../utils/lab-config';

type LabEntry = {
  config: LabConfig;
  category: string;
  slug: string;
};

type ResolvedEntry = LabEntry & { compName: string };

const REACT_FRAMEWORKS: LabFramework[] = ['react-vite', 'next-app'];
const VANILLA_FRAMEWORKS: LabFramework[] = ['javascript', 'typescript'];
const PYTHON_FRAMEWORKS: LabFramework[] = ['python'];
const KNOWN_FRAMEWORKS: LabFramework[] = [...REACT_FRAMEWORKS, ...VANILLA_FRAMEWORKS, ...PYTHON_FRAMEWORKS];

function componentExt(framework: LabFramework): string {
  if (framework === 'javascript') return '.js';
  if (framework === 'typescript') return '.ts';
  if (framework === 'vue-vite') return '.vue';
  if (framework === 'python') return '.py';
  return '.tsx';
}

async function resolveComponentName(
  category: string,
  slug: string,
  framework: LabFramework,
): Promise<string> {
  const ext = componentExt(framework);
  const srcDir = path.join(repoRoot, 'labs', category, slug, 'src');
  const conventional = toComponentName(slug);

  if (await fs.pathExists(path.join(srcDir, `${conventional}${ext}`))) {
    return conventional;
  }

  const files = await fg(`*${ext}`, { cwd: srcDir, deep: 1 });
  const main = files.map((f) => path.parse(f).name).find((n) => /^[A-Z]/.test(n));
  return main ?? conventional;
}

function generateReactLabsTs(entries: ResolvedEntry[], appDir: string): string {
  const lines: string[] = [
    `import type { ComponentType } from 'react';`,
    ``,
    `export type LabRoute = {`,
    `  id: string;`,
    `  title: string;`,
    `  route: string;`,
    `  component: ComponentType;`,
    `};`,
    ``,
  ];

  if (entries.length > 0) {
    for (const { category, slug, compName } of entries) {
      const importPath = path.relative(
        path.join(appDir, 'src'),
        path.join(repoRoot, 'labs', category, slug, 'src', compName),
      ).replace(/\\/g, '/');
      lines.push(`import ${compName} from '${importPath}';`);
    }
    lines.push(``);
  }

  const items = entries.map(({ config, compName }) => {
    return `  {\n    id: '${config.id}',\n    title: '${config.title}',\n    route: '${config.route}',\n    component: ${compName},\n  }`;
  });

  const labsValue = items.length > 0 ? `[\n${items.join(',\n')},\n]` : `[]`;
  lines.push(`export const labs: readonly LabRoute[] = ${labsValue};`);
  lines.push(``);

  return lines.join('\n');
}

function generateVanillaLabsTs(entries: ResolvedEntry[], appDir: string): string {
  const lines: string[] = [
    `export type LabRoute = {`,
    `  id: string;`,
    `  title: string;`,
    `  route: string;`,
    `  setup: (root: HTMLElement) => void;`,
    `};`,
    ``,
  ];

  if (entries.length > 0) {
    for (const { category, slug, compName } of entries) {
      const importPath = path.relative(
        path.join(appDir, 'src'),
        path.join(repoRoot, 'labs', category, slug, 'src', compName),
      ).replace(/\\/g, '/');
      lines.push(`import ${compName} from '${importPath}';`);
    }
    lines.push(``);
  }

  const items = entries.map(({ config, compName }) => {
    return `  {\n    id: '${config.id}',\n    title: '${config.title}',\n    route: '${config.route}',\n    setup: ${compName},\n  }`;
  });

  const labsValue = items.length > 0 ? `[\n${items.join(',\n')},\n]` : `[]`;
  lines.push(`export const labs: readonly LabRoute[] = ${labsValue};`);
  lines.push(``);

  return lines.join('\n');
}

function generatePythonLabsPy(entries: ResolvedEntry[], appDir: string): string {
  const lines: string[] = [
    '# auto-generated by lab:routes — do not edit manually',
    'import os',
    'import importlib.util',
    '',
    '',
    'def _load(rel: str, name: str):',
    '    abs_path = os.path.join(os.path.dirname(__file__), rel)',
    '    mod_dir = os.path.dirname(abs_path)',
    '    import sys',
    '    sys.path.insert(0, mod_dir)',
    '    spec = importlib.util.spec_from_file_location(name, abs_path)',
    '    mod = importlib.util.module_from_spec(spec)',
    '    spec.loader.exec_module(mod)',
    '    sys.path.pop(0)',
    '    return mod',
    '',
    '',
  ];

  for (const { category, slug, compName } of entries) {
    const relPath = path.relative(
      path.join(appDir, 'src'),
      path.join(repoRoot, 'labs', category, slug, 'src', `${compName}.py`),
    ).replace(/\\/g, '/');
    lines.push(`_${compName} = _load('${relPath}', '${compName}')`);
  }

  if (entries.length > 0) lines.push('');

  const items = entries.map(
    ({ config, compName }) =>
      `    {\n        "id": "${config.id}",\n        "title": "${config.title}",\n        "route": "${config.route}",\n        "setup": _${compName}.setup,\n        "router": getattr(_${compName}, 'router', None),\n    }`,
  );

  const labsValue = items.length > 0 ? `[\n${items.join(',\n')},\n]` : '[]';
  lines.push(`labs = ${labsValue}`);
  lines.push('');

  return lines.join('\n');
}

export async function routesCommand(): Promise<void> {
  const configPaths = await fg('labs/*/*/lab.config.ts', { cwd: repoRoot });

  const allEntries = await Promise.all(
    configPaths.map(async (configPath) => {
      const parts = configPath.split('/');
      const category = parts[1]!;
      const slug = parts[2]!;
      const labId = `${category}/${slug}`;
      const config = await readLabConfig(labId);
      return { config, category, slug } satisfies LabEntry;
    }),
  );

  const resolvedEntries = await Promise.all(
    allEntries.map(async (entry) => ({
      ...entry,
      compName: await resolveComponentName(entry.category, entry.slug, entry.config.framework),
    })),
  );

  const byFramework = new Map<LabFramework, ResolvedEntry[]>();
  for (const entry of resolvedEntries) {
    const fw = entry.config.framework;
    if (!byFramework.has(fw)) byFramework.set(fw, []);
    byFramework.get(fw)!.push(entry);
  }

  let totalSynced = 0;

  for (const fw of KNOWN_FRAMEWORKS) {
    const appDir = appDirs[fw];
    if (!appDir) continue;

    const isPython = PYTHON_FRAMEWORKS.includes(fw);
    const generatedPath = path.join(appDir, isPython ? 'src/labs_generated.py' : 'src/labs.generated.ts');
    if (!(await fs.pathExists(appDir))) continue;

    const entries = byFramework.get(fw) ?? [];
    const content = isPython
      ? generatePythonLabsPy(entries, appDir)
      : REACT_FRAMEWORKS.includes(fw)
      ? generateReactLabsTs(entries, appDir)
      : generateVanillaLabsTs(entries, appDir);

    await fs.writeFile(generatedPath, content);
    totalSynced += entries.length;
    console.log(`  [${fw}] ${entries.length} lab(s) → ${path.relative(repoRoot, generatedPath)}`);
  }

  console.log(`Synced ${totalSynced} lab(s) total across ${KNOWN_FRAMEWORKS.length} framework(s).`);
}
