# auto-generated by lab:routes — do not edit manually
import os
import importlib.util


def _load(rel: str, name: str):
    abs_path = os.path.join(os.path.dirname(__file__), rel)
    spec = importlib.util.spec_from_file_location(name, abs_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


labs = []
